/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -a manager/dbus/dbusbackendwrapperadaptor -i dbusbackendwrapper.h -l PublicTransportation::DBusBackendWrapper common/dbus/backend.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSBACKENDWRAPPERADAPTOR_H_1350055340
#define DBUSBACKENDWRAPPERADAPTOR_H_1350055340

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "dbusbackendwrapper.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.SfietKonstantin.publictransportation
 */
class PublictransportationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.SfietKonstantin.publictransportation")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.SfietKonstantin.publictransportation\">\n"
"    <!-- Method for registration -->\n"
"    <method name=\"registerBackend\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"capabilities\"/>\n"
"    </method>\n"
"    <!-- Method used to transmit that something wrong happened -->\n"
"    <method name=\"registerError\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"error\"/>\n"
"    </method>\n"
"    <!-- Copyright -->\n"
"    <signal name=\"copyrightRequested\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"request\"/>\n"
"    </signal>\n"
"    <method name=\"registerCopyright\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"request\"/>,\n"
"            <arg direction=\"in\" type=\"s\" name=\"copyright\"/>,\n"
"        </method>\n"
"    <!-- Autocompletion for station search -->\n"
"    <signal name=\"suggestStationsRequested\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"partialStation\"/>\n"
"    </signal>\n"
"    <method name=\"registerSuggestedStations\">\n"
"      <annotation value=\"const QList&lt;PublicTransportation::Station> &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"request\"/>,\n"
"            <arg direction=\"in\" type=\"a(a{sv}sa{sv})\" name=\"suggestedStations\"/>\n"
"    </method>\n"
"    <!-- All journeys from a station -->\n"
"    <signal name=\"journeysFromStationRequested\">\n"
"      <annotation value=\"const PublicTransportation::Station &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"out\" type=\"(a{sv}sa{sv})\" name=\"station\"/>\n"
"      <arg direction=\"out\" type=\"i\" name=\"limit\"/>\n"
"    </signal>\n"
"    <method name=\"registerJourneysFromStation\">\n"
"      <annotation value=\"const QList&lt;PublicTransportation::InfoJourneys> &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"in\" type=\"a((a{sv}sa{sv})(a{sv}sa{sv})a((a{sv}sa{sv})(a{sv}sa{sv})))\" name=\"infoJourneys\"/>\n"
"    </method>\n"
"    <!-- Waiting time for a journey -->\n"
"    <signal name=\"waitingTimeRequested\">\n"
"      <annotation value=\"const PublicTransportation::Company &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <annotation value=\"const PublicTransportation::Line &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In2\"/>\n"
"      <annotation value=\"const PublicTransportation::Journey &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In3\"/>\n"
"      <annotation value=\"const PublicTransportation::Station &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In4\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"out\" type=\"(a{sv}sa{sv})\" name=\"company\"/>\n"
"      <arg direction=\"out\" type=\"(a{sv}sa{sv})\" name=\"line\"/>\n"
"      <arg direction=\"out\" type=\"(a{sv}sa{sv})\" name=\"journey\"/>\n"
"      <arg direction=\"out\" type=\"(a{sv}sa{sv})\" name=\"station\"/>\n"
"    </signal>\n"
"    <method name=\"registerWaitingTime\">\n"
"      <annotation value=\"const QList&lt;PublicTransportation::WaitingTime> &amp;\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"in\" type=\"a(ia{sv})\" name=\"waitingTimeList\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    PublictransportationAdaptor(PublicTransportation::DBusBackendWrapper *parent);
    virtual ~PublictransportationAdaptor();

    inline PublicTransportation::DBusBackendWrapper *parent() const
    { return static_cast<PublicTransportation::DBusBackendWrapper *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void registerBackend(const QStringList &capabilities);
    void registerCopyright(const QString &request, const QString &copyright);
    void registerError(const QString &request, const QString &error);
    void registerJourneysFromStation(const QString &request, const QList<PublicTransportation::InfoJourneys> & infoJourneys);
    void registerSuggestedStations(const QString &request, const QList<PublicTransportation::Station> & suggestedStations);
    void registerWaitingTime(const QString &request, const QList<PublicTransportation::WaitingTime> & waitingTimeList);
Q_SIGNALS: // SIGNALS
    void copyrightRequested(const QString &request);
    void journeysFromStationRequested(const QString &request, const PublicTransportation::Station & station, int limit);
    void suggestStationsRequested(const QString &request, const QString &partialStation);
    void waitingTimeRequested(const QString &request, const PublicTransportation::Company & company, const PublicTransportation::Line & line, const PublicTransportation::Journey & journey, const PublicTransportation::Station & station);
};

#endif
